### ISSUE TITLE
Find all user with meta value

### ISSUE THREAD

**Issue by cracki** [chrismichaels84/eloquent-meta#16]
Hi
how i can find all user who have same meta ?
thx

**Comment by chrismichaels84** [comment]
I am not sure this is possible currently. Let me investigate today.

**Comment by chrismichaels84** [comment]
Still working on this. I have added a small patch to the new `entities` branch that allows you to:
```php
$meta = Phoenix\EloquentMeta\Meta::find(1);
$meta->setEntity('User');

foreach ($meta->entity as $user) {
    echo $user->email;
}
```
return all the users attached to a specific Meta record. The problem is that there is (currently) no way to attach a single meta record to multiple entities. For instance, if you add "last name" meta to several users, it still creates a new row for each instance.

Therefore, all the users with lastname meta = 'wilson' would still have sever records for metadata.

Can you give me a use case you are trying to make work? Some code would be great.

**Comment by cracki** [comment]
Good news, thank you
I wants to develop an online user manager.
This system needs some parameters (as meta) for users like "position".
Then we need to query users by this meta and list them.

user1->meta(position)=1 
user2->meta(position)=1
user3->meta(position)=2

With this new "entities", can we query "user" where "meta position" is 1 and get "user 1 and user 2" ?

**Comment by chrismichaels84** [comment]
No, because there would actually be three different Meta records created here. Even though the name and value would be the same for each, they would have their own ID. I will have to do some thinking about how to make this work, but I'm not sure its possible without a major rewrite.

If this use case is so important, why not just add a "position" column to your users table? Meta is really a way to cheat and add unstructured data to a structured database. If this is something you expect all or most users to have, its best to add it to the users table.

**Comment by cracki** [comment]
Adding meta to tables is the right way for our work because  we have about 25 value from user and maybe this go to 35 in future... this happens to Team, Tickets, Projects, ... tables

This git "https://github.com/mmanos/laravel-metable" can solve my problem because  we can "$users = User::withMeta('employer')->take(10)->get();".
With your nice package , we just have single Metas table and this is better than "mmanos" that each table have seperate meta and table_meta table

**Comment by chrismichaels84** [comment]
Thanks. I'll have a look at the other to see how I can improve :smile:
