### ISSUE TITLE
Nested Meta Data

### ISSUE THREAD

**Issue by jandayanan** [chrismichaels84/eloquent-meta#18]
Does the current release allow nested set of meta data? Or do you plan to release a version with a nested meta data set? It could be useful in a lot of cases, so I am wondering if you are planning to develop this. Thanks!

**Comment by chrismichaels84** [comment]
The current version does not manage nested data, and I'm not sure how that would work in a traditional sql-like database. I do have another library [chrismichaels84/data-manager](https://github.com/chrismichaels84/data-manager) which is an array library that handles nested data.

I would be happy to investiage this functionality, but how do you picture it being persisted to the actual database? What schema would make sense for that? A parent field in each meta item row? Using array-dot-notation as the key?

It would also be helpful to see a use case with some desired api code. How would you see using this feature?

**Comment by jandayanan** [comment]
Hi @chrismichaels84 

Thank you for the response. The use case is simple: grouped meta data.
Consider the following array:

``` php
$meta = [
	"personal_information" => [
		"first_name" => "John",
		"last_name" => "Doe",
		"address" => [
			"street" => "14th Ave.",
			"city" => "New York"
		]
	]
];
```

It can be helpful for lots of use cases too, but this is just an example. The data schema is not that complex. By adding a parent_id with a default value of `null`, you can create a tree node of meta data. You can also do it like what you do with arrays now which is a JSON encoded string, although it may have some implications for later parts.

As for the desired API code, I took a look at your data manager package, and I think it can be similar to that one. Like:

``` php
/* Basic Usage. All works with dot notation as well */
$manager->add('name', 'value');
$manager->add('some.nested.data', 3); // Use dot notation for namespacing or nesting
$manager->get('name'); // 'value'
$manager->get('doesntexist', 'fallback'); // 'fallback'
$manager->get('doesntexist') // throws an ItemNotFoundException with no fallback
$manager->getIfHas('doesntexist') // returns a NoItemFoundMessage instead of a script-stopping exception
$manager->getAll(); // returns array of all items
$manager->all(); // returns array of all items
$manager->exists('name'); // true
$manager->exists('some.starting.data'); // true
$manager->exists('nope'); // false
```

**Comment by chrismichaels84** [comment]
I won't have a lot of time soon to look at this, but a glance through tells me that this may overcomplicate things a bit. It would allow for duplicate keys, which could be a problem. If the same meta model had `one.two.three = "something"` and `three = "something else"`, both keys would be `three`. In order to really be safe, the `Meta` trait would have to check for parents all the way up the chain to ensure the right value is being returned. That seems like a performance waste to me.

Storing serialized arrays is an option, but that's super sloppy and you couldn't dig into it.

The other option would be to fake it: set the keys to the full namespace `one.two.three` and use a simple parser to combine things when `getAllMeta()` is used. That, however, leads to the problem of having to check through the entire table for children each time you want an item. So if the user does `getMeta("one.two")`, the model would have to look through the entire table to see if any of the records for this model have a "two" as their parent, query that, and do the same recursively, in order to return a full array.

Again, this seems like a performance drag when the vast majority of people wouldn't use this feature.

It would be conceivable to include a second trait `NestedMeta` that adds this functionality, and the user would just have to decide if the potential performance hit is worth the use of nesting. In many cases, it wouldn't be terrible, just bad in cases with a LOT of records and nesting.
